language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); Pkg.add("Coverage")'
  - julia -e 'using Coverage; import Twiddle; cd(dirname(dirname(pathof(Twiddle)))); Codecov.submit(process_folder())'
  - julia -e 'import Twiddle; cd(dirname(dirname(pathof(Twiddle)))); include(joinpath("docs", "make.jl"))'
