name = "Twiddle"
uuid = "7200193e-83a8-5a55-b20d-5d36d44a0795"
authors = ["Ben J. Ward <benjward@protonmail.com", "Luis Yanes"]
version = "1.1.1"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]